import streamlit as st
import pandas as pd
from expense_agent.agent import analyze_expenses

# ==========================================
# 1. PAGE CONFIGURATION & STYLING
# ==========================================
st.set_page_config(
    page_title="EcoSphere: Carbon & Air Quality Analytics",
    page_icon="🌱",
    layout="wide"
)

# Custom dark theme overrides for production
st.markdown("""
    <style>
    .main { background-color: #0e1117; }
    h1, h2, h3 { color: #ffffff; }
    .stButton>button {
        background-color: #ff4b4b;
        color: white;
        border-radius: 6px;
        border: none;
        padding: 0.5rem 2rem;
    }
    .stButton>button:hover { background-color: #ff3333; }
    div[data-testid="stExpander"] {
        background-color: #1a1c23;
        border: 1px solid #2d3139;
        border-radius: 6px;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. MAIN DASHBOARD HEADER
# ==========================================
st.markdown("# 🌱 EcoSphere: Carbon & Air Quality Analytics")
st.caption("AI-Powered Environmental Auditing across Transport Sectors and Product Lifecycles")
st.markdown("---")

user_input = st.text_area(
    "Enter your activities for today (e.g., 'drove my car for 20km, used 2 paper cups'):", 
    value="", 
    height=120,
    key="main_user_text_area"
)

# ==========================================
# 3. EXECUTE COOPERATIVE AGENT PIPELINE
# ==========================================
if st.button("Analyze Footprint"):
    if not user_input.strip():
        st.warning("Please type your activity log before running the analysis.")
    else:
        with st.spinner("Spawning agent instances and running data analytics execution trace..."):
            try:
                report = analyze_expenses(user_input)
                st.success("Analysis Complete!")
                
                # --------------------------------------
                # DISPLAY LIVE AGENT TRACE LOGS
                # --------------------------------------
                if hasattr(report, 'agent_reasoning_logs') and report.agent_reasoning_logs:
                    with st.expander("👁️ View Multi-Agent Execution & Reasoning Trace", expanded=True):
                        st.markdown("### 🤖 Collaborative Agent Chain-of-Thought Logs")
                        for log_line in report.agent_reasoning_logs:
                            if "Agent 1" in log_line:
                                st.markdown(f"🔵 **{log_line}**")
                            elif "Agent 2" in log_line:
                                st.markdown(f"⚙️ `{log_line}`")
                            elif "Agent 3" in log_line:
                                st.markdown(f"🟢 *{log_line}*")
                            else:
                                st.markdown(f"&nbsp;&nbsp;&nbsp;&nbsp;{log_line}")
                
                # --------------------------------------
                # RENDER DATA TABLE
                # --------------------------------------
                st.markdown("## 📋 Transit Environmental Report")
                
                table_rows = []
                if hasattr(report, 'activities') and report.activities:
                    for act in report.activities:
                        table_rows.append({
                            "Category": act.category,
                            "Transit Mode / Asset": act.metric,
                            "Distance / Quantity": f"{act.value:.2f}" if act.unit == "km" else f"{int(act.value)}",
                            "Unit": act.unit,
                            "CO2 Status": f"{act.co2_kg:+.2f} kg (Emitted)" if act.co2_kg > 0 else (f"{act.co2_kg:.2f} kg (Saved)" if act.co2_kg < 0 else "0.00 kg (Neutral)"),
                            "Air Quality PM2.5 Status": f"{act.pm25_g:+.3f} g (Emitted)" if act.pm25_g > 0 else (f"{act.pm25_g:.3f} g (Prevented)" if act.pm25_g < 0 else "0.000 g (Neutral)")
                        })
                
                if table_rows:
                    df = pd.DataFrame(table_rows)
                    st.table(df)
                else:
                    st.info("No rows generated by the Auditor Agent.")
                
                # --------------------------------------
                # CONSOLIDATED SUMMARY CARDS
                # --------------------------------------
                st.markdown("## 📊 Consolidated Travel Summary")
                col1, col2 = st.columns(2)
                
                with col1:
                    st.markdown("**Net Carbon Balance**")
                    net_co2 = getattr(report, 'total_net_co2_kg', 0.0)
                    color_prefix = "🔴" if net_co2 > 0 else "🟢"
                    st.markdown(f"## {color_prefix} {net_co2:+.2f} kg")
                    st.caption("Net Carbon Footprint Status")
                    
                with col2:
                    st.markdown("**Total PM2.5 Released**")
                    net_pm = getattr(report, 'total_pm25_g', 0.0)
                    st.markdown(f"## 🟣 {net_pm:.3f} g")
                    st.caption("Respiratory Atmospheric Footprint")
                
                # --------------------------------------
                # ECO-COACH INSIGHTS FOOTER
                # --------------------------------------
                st.markdown("---")
                tip = getattr(report, 'green_actionable_tip', 'No strategy generated.')
                st.info(f"💡 **Eco-Coach Actionable Strategy:** {tip}")
                
            except Exception as e:
                st.error("🚨 Frontend Rendering Exception Caught!")
                st.exception(e)